[package]
name = "reve-midi-wasm"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/reinshit/revelation-midi-converter"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
midi-to-mml = { path = "../lib" }
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
